DATABASE:
  DB_DRIVER: postgres
  DB_SOURCE: postgresql://root:secret@localhost:5432/gestapo?sslmode=disable

SERVER_ADDRESS: 0.0.0.0:8080

TOKEN_SYMMETRIC_KEY: "12345678901234567890123456789012"

TWILIO:
  ACCOUNT_SID: AC8961fe0be19724fe35f48e44bbce05ad
  AUTH_TOKEN: 852c0a1c7571014ebbef12ea27c1f898
  SERVICE_SID: VA0b4d71c435b654f8f3954af8f07fbb7b

EMAIL:
  SENDER_NAME: GESTAPO
  SENDER_ADDRESS: gestapo.test@gmail.com
  SENDER_PASSWORD: qvwltpeeufqieffo

REDIS_SERVER:
  # USERNAME: testuser
  ADDRESS: localhost:6379
  PASSWORD: ""
  DB: 0
