version: "3.8"

services:
  # TODO:fix it later
  postgres:
    image: postgres:16-alpine
    container_name: postgres16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gestapo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d gestapo"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  authentication-service:
    build:
      context: ./
      dockerfile: ./authentication-service.dockerfile    
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/gestapo?sslmode=disable        
    restart: always  
    depends_on:
      postgres:
        condition: service_healthy  
