version: "3.8"

services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gestapo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d gestapo"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  redis:
    image: redis:7.2-alpine
    container_name: redis7.2
    restart: always  
    ports:
      - 6379:6379
    depends_on:
      postgres:
        condition: service_healthy  

  grpc-gateway:
    build:
      context: ./
      dockerfile: ./grpc-gateway.dockerfile
    ports:
      - "9000:80"
    depends_on:
      - authentication-service
       

  authentication-service:
    build:
      context: ./
      dockerfile: ./authentication-service.dockerfile    
    ports:
      - "9001:80"
    # TODO:fix it later  
    # environment:
    #   - DB_SOURCE=postgresql://root:secret@postgres:5432/gestapo?sslmode=disable        
    # restart: always  
    depends_on:
      postgres:
        condition: service_healthy  
